before_script:
  - source /etc/profile
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN acr.run

services:
  - docker:dind

stages:
  - build
  - test

image_build:
  stage: build
  script: ./c/build
  only:
    refs:
      - master
      - merge_requests
    changes:
      - c/install
      - c/pipinstall
      - c/config
      - Dockerfile
      - Dockerfile.build
      - Pipfile
      - Pipfile.lock
      - setup.cfg
      - setup.py
      - MANIFEST.in

pytest:
  only:
    refs:
      - master
      - merge_requests
  stage: test
  script: ./c/test pytest manabi

flake8:
  only:
    refs:
      - master
      - merge_requests
  stage: test
  script: ./c/test flake8 manabi

mypy:
  only:
    refs:
      - master
      - merge_requests
  stage: test
  script: ./c/test mypy manabi

isort:
  only:
    refs:
      - master
      - merge_requests
  stage: test
  script: ./c/test isort --check-only manabi

black:
  only:
    refs:
      - master
      - merge_requests
  stage: test
  script: ./c/test black --check manabi
