name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  standard-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install libsodium
        run: sudo apt-get install -y libsodium23

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install virtual-env
        run: |
          pip install -U pip
          pip install -U poetry
          poetry install

      - name: Run tests
        continue-on-error: true
        run: poetry run pytest manabi

      - name: Run flake8
        continue-on-error: true
        run: poetry run flake8 manabi && false

      - name: Run mypy
        continue-on-error: true
        run: poetry run mypy manabi

      - name: Run isort
        continue-on-error: true
        run: poetry run isort --check-only manabi

      - name: Run black
        continue-on-error: true
        run: poetry run black --check manabi
