name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  standard-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install libsodium
        run: apt-get install -y libsodium23
      - name: Install virtual-env
        run: poetry install
